### ISSUE TITLE
Ability to add timeout blocks

### ISSUE THREAD

**Issue by madelaney** [elct9620/terraform-provider-lambdalabs#10]
I was trying to use your module to do a simple apply (see below) but I got a timeout operation while waiting for the machine to becoming available.

Normally, I would just update the timeout (https://developer.hashicorp.com/terraform/language/resources/syntax#operation-timeouts) but this module doesn't seem to support that block.

```terraform
resource "lambdalabs_instance" "stable_diffusion" {
  name               = "stable_diffusion"
  region_name        = "us-west-1"
  instance_type_name = "gpu_1x_a10"
  ssh_key_names = [
    lambdalabs_ssh_key.primary.name
  ]

  connection {
    type        = "ssh"
    user        = "ubuntu"
    private_key = file(local.ssh_private_key)
    host        = self.ip
  }

  provisioner "remote-exec" {
    inline = [
      "env | sort"
    ]
  }
}

```

**Comment by elct9620** [comment]
After I check the terraform SDK. I didn't implement the timeout support. I will check for how to support it.

**Comment by elct9620** [comment]
Timeout supported after `v0.3.0` (https://registry.terraform.io/providers/elct9620/lambdalabs/0.3.0)

Tested with
```hcl
timeotus {
  create = "30m"
}
```
